### ISSUE TITLE
Elevator pitch

### ISSUE THREAD

**Issue by DanLawrence91** [SEO-Web/TeamRepo#15]
Thought something along these lines initially - open to suggestions to improve it:

"There is a big push towards consuming local in the world today and beer is no exception. Local breweries often produce a better, more interesting product, but are much harder to find than large chains. 

This is where Plan Your Crawl specialise. Enter you chosen location and find details for local breweries and bottleshops in that area. Build your tour around these quality establishments, along with finding out the weather for your destination to help you plan and enjoy everywhere you visit!"

**Comment by skipsterling** [comment]
I've just added a little extra padding to get us closer to the minute mark.
Just a bit of an intro of who we are and what we have created and the value that we provide when the consumer uses our product.
 It now goes for roughly 50 seconds now. Let me know if you think it still needs more or if I should scrap it and start again? 


"We are Group 3, the creators of Plan your Crawl and we help beer enthusiasts find the best breweries in their location by assisting in the creation of a customised brewery tour, all from the palm of your hand. 

There is a big push towards consuming local in the world today and beer is no exception. Local breweries often produce a better, more interesting product, but are much harder to find than large chains.
This is where Plan Your Crawl specialise. Enter you chosen location and find details for local breweries and bottle-shops in that area. Build your tour around these quality establishments, along with finding out the weather for your destination to help you plan and enjoy everywhere you visit!

By using our website you have removed the element of stress from your holiday leaving you more time to enjoy the important things in life."
